from .penguin import Penguin
from .painted_dog import PaintedDog
from .ant import Ant
from .betta import Betta
from .copperhead import Copperhead
from .earthworm import Earthworm
from .finch import Finch
from .gerbil import Gerbil
from .mouse import Mouse
from .parakeet import Parakeet
from .terrapin import Terrapin
from .timber_rattlesnake import TimberRattlesnake